### ISSUE TITLE
ARG CACHE_MEM not picked up?

### ISSUE THREAD

**Issue by eduarddrenth** [duncdrum/distroless-exist#18]
It looks like ```--build-arg CACHE_MEM=1024``` isn't being picked up (because of distroless I think), I see:

```
getConfigAttributeValue]:1513) - Configuration value overridden by system property: org.exist.db-connection.cacheSize, with value: 256M
```

**Comment by duncdrum** [comment]
hmm that is strange, what was the full command you used to supply the new value?

**Comment by eduarddrenth** [comment]
Actually I think the problem is:
- I pull in duncdrum/existdb:6.0.0-j8 (prebuilt) in my own Dockerfile
- the CACHE_MEM arg isn't evaluated because ENV JAVA_TOOL_OPTIONS is not in my Dockerfile

**Comment by duncdrum** [comment]
Yes the build arg works, on the docker files here. If these are used as base image the arg needs to be included in the same way as they are here, within the new dockerfile. This is by design.

**Comment by eduarddrenth** [comment]
Looks like it doesn't work, my Dockerfile:

```
# syntax=docker/dockerfile:experimental
FROM existdb/existdb:6.0.1

ENV CLASSPATH=/exist/lib/*
ARG CACHE_MEM=1024

COPY *.xar $EXIST_HOME/autodeploy/

RUN --mount=type=bind,source=data,target=/data --mount=type=secret,id=adminpw,required,target=/tmp/adminpw [ "java", "org.exist.start.Main", "client", "--no-gui",  "-l", "-u", "admin", "-P", "", "-F", "/tmp/adminpw" ]
```
My log says:
```
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8   -Dsun.jnu.encoding=UTF-8   -Djava.awt.headless=true   -Dorg.exist.db-connection.cacheSize=256M   -Dorg.exist.db-connection.pool.max=20   -Dlog4j.configurationFile=/exist/etc/log4j2.xml   -Dexist.home=/exist   -Dexist.configurationFile=/exist/etc/conf.xml   -Djetty.home=/exist   -Dexist.jetty.config=/exist/etc/jetty/standard.enabled-jetty-configs   -XX:+UnlockExperimentalVMOptions   -XX:+UseCGroupMemoryLimitForHeap   -XX:+UseG1GC   -XX:+UseStringDeduplication   -XX:MaxRAMFraction=1   -XX:+ExitOnOutOfMemoryError
Configuration value overridden by system property: org.exist.db-connection.cacheSize, with value: 256M
```
It probably works when I override the ENV JAVA_TOOL_OPTION, but precisely that is what I don't want to do, because I want to rely on what has been figured out in the community.

**Comment by eduarddrenth** [comment]
So the ${CACHE_MEM} in ENV JAVA_TOOL_OPTION isn't evaluated after my FROM. This could be by (docker) design (cannot find clarity in docs, stackoverflow, ...), or because of the missing shell in the distroless image.

**Comment by duncdrum** [comment]
You can try with `duncdrum/existdb:debug` to get a shell base image. I would expect it to not work however. My understanding of the docker specs is that both tool options and arg would need to be on the new dockerfile. 

The arg does work as intended when using the docker files from this repo. Both values can be configured by modifying `conf.xml` which I expect most users want to do anyways.

**Comment by eduarddrenth** [comment]
You're right about the debug, doesn't work
conf.xml doesn't work out of the box either, because `-Dorg.exist.db-connection.cacheSize=...` from the Dockerfile overrides it
I can of course solve the problem, it just doesn't satisfy me

**Comment by eduarddrenth** [comment]
I choose the solution to copy and adapt JAVA_TOOL_OPTION in my compose file and (document to) compare this every now and than with JAVA_TOOL_OPTION in the Dockerfile.

**Comment by duncdrum** [comment]
sounds good the relevant section of the docker docs is [Using ARG variables](https://docs.docker.com/engine/reference/builder/#using-arg-variables)

I don't see anyway around needing the `JAVA_TOOL_OPTIONS` as `ENV` in the images here. I ll experiment a bit further with having `conf.xml` changes be more useful for base images.
