### ISSUE TITLE
new classpath mechanism

### ISSUE THREAD

**Issue by duncdrum** [duncdrum/distroless-exist#8]
see #7 

see https://github.com/eXist-db/exist/issues/3362#issuecomment-1024040700

https://github.com/duncdrum/distroless-exist/blob/7db54282c4327e687a6ee5f41ba09079f69f6860/Dockerfile#L42

**Comment by eduarddrenth** [comment]
looks way better than the uber jar, this way I don't have to manipulate the classpath for a RUN command

**Comment by duncdrum** [comment]
that was the idea, please let me know if you see any problems. Thanks for testing

**Comment by eduarddrenth** [comment]
works fine, one thing I saw is monex console stays disconnected, perhaps related to websockets issue I saw in slack
